name: publish-all-cn

on:
  workflow_dispatch:
  schedule:
    - cron: "01 16 * * 4"
  push:
    branches:
      - main

concurrency:
  group: publish-all-cn
  cancel-in-progress: true

jobs:
  publish-all-cn:
    uses: ./.github/workflows/template-publish-all.yml
    with:
      CN_FLAG: true
      WORKFLOW_REF: publish-all-cn.yml
    secrets: inherit
